config/routes.rb
Threesquare::Application.routes.draw do

  root 'locations#index'
  resources :locations

end

app/models/location.rb
class Location < ActiveRecord::Base
	def snippet
		self.review.truncate(60)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def index
		@locations = Location.all
	end

	def show
		@location = Location.find(params[:id])
	end

	def new
		@location = Location.new
	end

	def create
		@location = Location.new(location_params)
		@location.save
		redirect_to root_path
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])
		@location.update(location_params)
		redirect_to root_path
	end

	def destroy
		@location = Location.find(params[:id])
		@location.destroy
		redirect_to root_path
	end

	private
	def location_params
		params.require(:location).permit(:name, :picture_url, :review)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Threesquare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
	<div clas="field">
		<%= f.label :Location_Name %>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :picture_url %>
		<%= f.text_field :picture_url %>
	</div>

	<div class="field">
		<%= f.label :review %>
		<%= f.text_field :review %>
	</div>

	<%= f.submit %>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit a Location</h1>

<%= render "form" %>

app/views/locations/index.html.erb
<h1>Austin's Favorite Spots</h1>



<table>
	<thead>
		<tr>Location</tr>
	</thead>

	<tbody>
		<% @locations.each do |location| %>
			<tr>
				<td><%= image_tag location.picture_url, width: "100" %> </td>
				<td><%= location.name %></td>
				<td><%= location.snippet %></td>
				<td><%= link_to "Show", location %></td>
				<td><%= link_to "Edit", edit_location_path(location) %></td>
				<td><%= link_to "Remove", location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/locations/new.html.erb
<h1>Add a New Location</h1>

<%= render "form" %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>

<%= image_tag @location.picture_url, width: "75%" %>

<p><%= @location.review %></p>

<p><%= link_to 'Home', root_path %></p>